# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nshint.github.io
title: NSHint
subtitle:
author: NSHint
simple_search: https://www.google.com/search
description:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /blog/:year/:month/:day/:title/
timezone: Europe/Warsaw
source: source
destination: public
code_dir: downloads/code
category_dir: blog/categories

paginate: 10          # Posts per page on the blog index
paginate_path: "posts/:num"
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: nshintio
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false

social:
  twitter: https://twitter.com/nshintio
  github: https://github.com/nshint/
  rss: https://nshint.github.io/atom.xml

author_ids: [matt, woj, rafa, marcin, kondrat]
authors:
   matt:
      display_name: Mateusz Matoszko
      email: nshint@matoszko.pl
      twitter: mmatoszko
      github: mmatoszko
   wojtek:
      display_name: Wojciech Łukaszuk
      email: wojtek@nshint.io
      twitter: wojteklu
      github: wojteklu
   rafa:
      display_name: Rafael Machado
      twitter: rakaramos
      github: rakaramos
   marcin:
        display_name: Marcin Małysz
        email: marcin@nshint.io
        twitter: noxytrux
        github: noxytrux
   kondrat:
        display_name: Kondrat Kielar
        email: kondratk@gmail.com
        twitter: Maroreram
        github: kondratk
